name: Deploy Native MacOS Application

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup GraalVM built by Gluon
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make staging directory
        run: mkdir staging

      - name: Gluon Build
        run: mvn -Pdesktop gluonfx:build gluonfx:package

      - name: Copy native image to staging
        run: cp -r target/gluonfx/x86_64-darwin/ExviFitness* staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: stagingtaging