name: Build Jars For Desktop Platforms

on:
  push:
    branches:
      kotlin

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Clone Core Repository
        uses: actions/checkout@v2
        with:
          name: CallumMackenzie/exvi-core
          path: exvi-core-cloned
      - run: |
            cd ./exvi-core-cloned
            ls
      - name: Validate Core Gradle Wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish Core to Maven Local
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: publishToMavenLocal
    
      - name: Clone Client Repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: packageUberJarForCurrentOS

      - name: Archive Ubuntu Build
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-build
          path: desktop/build/compose/jars/*.jar

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Clone Core Repository
        uses: actions/checkout@v2
        with:
          name: CallumMackenzie/exvi-core
          path: exvi-core-cloned
      - run: cd ./exvi-core-cloned
      - name: Validate Core Gradle Wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish Core to Maven Local
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: publishToMavenLocal
    
      - name: Clone Client Repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: packageUberJarForCurrentOS

      - name: Archive Windows Build
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: desktop/build/compose/jars/*.jar

  build-osx:
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - name: Clone Core Repository
        uses: actions/checkout@v2
        with:
          name: CallumMackenzie/exvi-core
          path: exvi-core-cloned
      - run: cd ./exvi-core-cloned
      - name: Validate Core Gradle Wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish Core to Maven Local
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: publishToMavenLocal
    
      - name: Clone Client Repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: packageUberJarForCurrentOS

      - name: Archive MacOS Build
        uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: desktop/build/compose/jars/*.jar
